service:
  port: "8080"
  publicKeyLocation: "public_key_file_location"
  privateKeyLocation: "private_key_file_location"

database:
  host: "database_host"
  port: "5432"
  name: "database_name"
  username: "database_username"
  password: "database_password"

